server:
  port: 8082
spring:
  application:
    name: user-details-service
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: movieadmin123
#    url: jdbc:mysql://localhost:3306/movie_rating
#    username: movieadmin
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
